### ISSUE TITLE
Incorrect value for inverse when longitudes are equal

### ISSUE THREAD

**Issue by nicolas-UKLSL** [omdv/geovectors#1]
Calling `geovectorslib.inverse(lats1=[0], lons1=[1], lats2=[10], lons2=[1])` returns
```
{'s12': array([0.]),
 'azi1': array([nan]),
 'azi2': array([nan]),
 'iterations': 0}
```
while calling `geographiclib.geodesic.Geodesic.WGS84.Inverse(lat1=0, lon1=1, lat2=10, lon2=1)` returns 
```
{'lat1': 0,
 'lon1': 1.0,
 'lat2': 10,
 'lon2': 1.0,
 'a12': 9.967145322217904,
 's12': 1105854.8332343723,
 'azi1': 0.0,
 'azi2': 0.0}
```

Versions:
geographiclib.__version__='1.50'
geovertorslib version 1.1

**Comment by nicolas-UKLSL** [comment]
Proposed fix:
In geod.py, replace line 46
```
    delta = L
```
by 
```
    delta = np.atleast_1d(L)
    delta[delta < 1e-12] = 1.01e-12

```

**Comment by omdv** [comment]
@nicolas-UKLSL, thanks for reporting and catching this case, somehow I did not capture it. Looking into it.

**Comment by nicolas-UKLSL** [comment]
Hello again @omdv,
Having played a little with my proposed fix, it is actually buggy. Indeed, if . Looking at the issue, if lon2 << lon1, then L < 1e-12, yet delta should still be = L. So the proposed fix should, I think, be:
```
delta = np.atleast_1d(L)
delta[np.abs(delta) < 1e-12] = 1.01e-12
```
Hope this helps.

**Comment by omdv** [comment]
Hello @nicolas-UKLSL. Sorry - just had some uninterrupted time to look at it. Your proposed fix was good for this issue, but then other tests started failing. Instead I realized that when `delta` is zero it was skipping the converging loop, because I initialized `delta_prime` to be zero. Once I changed initial `delta_prime` to be very high - nothing else needed fixing.

Note, that in (rare?) case of equatorial points it can throw the warning on `numpy.true_divide`, but this is expected and won't affect convergence - didn't want to suppress warning, instead will think of how to omit those points from the loop.

Please upgrade to `geovectorslib==1.2` version.

```
>>> import geovectorslib
>>> geovectorslib.inverse(lats1=[0], lons1=[1], lats2=[10], lons2=[1])
{'s12': array([1105854.8332357]), 'azi1': array([0.]), 'azi2': array([0.]), 'iterations': 1}
```

**Comment by nicolas-UKLSL** [comment]
Thank you!
